print('Iremos calcular o preço total do aluguel de um carro!')
dia = int(input('Digite o quantidade de dias de aluguel: '))
km = int(input('Digite o quantidade de km rodados: '))
preço = (60*dia) + (0.15*km)
print(f'O preço total do aluguel foi de {preço} reais!')
